Danielhiversen/PyXiaomiGateway

- PyXiaomiGateway/__init__.py
Commented out command heartbeat for sensors notification to avoid false positive statuses.
Only report command is reliable and will notify home-assistant
> Fix from home assistant forum (cesco83): "Xiaomi body sensor gateway maybe wrong motion detection"

- PyXiaomiGateway/__init__.py
- setup.py
Entity id of the water leak sensor added. It's needed to integrate the sensor into the HA platform.
> Water leak sensor (sensor_wleak.aq1) added

- PyXiaomiGateway/__init__.py
Hi Daniel! What do you think about?
This is the counterpart: https://github.com/syssi/home-assistant/commit/9ae484a068f9d0f5814fd19fff8ae9820a800ee5
It needs some testing of docker users: https://community.home-assistant.io/t/xiaomi-gateway-not-discovered/25030/112
On my usual linux host and network it works fine.
> Static configuration of a host without discovery

- .travis.yml
- PyXiaomiGateway/__init__.py
- setup.py
> Switch to PyCryptoDome

- .travis.yml
- PyXiaomiGateway/__init__.py
- setup.py
Reverts Danielhiversen/PyXiaomiGateway#13
> Revert "Switch to PyCryptoDome"

- PyXiaomiGateway/__init__.py
There are no details known about the device. I hope it behaves like the other switches. 
Fixes #15.
> New wireless button (sensor_switch.aq3) added

- xiaomi_gateway/__init__.py
Related to https://github.com/home-assistant/home-assistant/pull/11631.
> Removed heartbeat filter for motion sensor, pass raw data to callbacks

- xiaomi_gateway/__init__.py
After we ask for a new token we have to regenerate the comand
@syssi : Could check this?
> regenerate cmd with new token

- setup.py
- xiaomi_gateway/__init__.py
> Add new cube model (sensor_cube.aqgl01)

- xiaomi_gateway/__init__.py
Hi Daniel
I add aqara lock support to hass.
I have tested in my house.
You can review the hass PR #14419
> Add aqara lock support

- xiaomi_gateway/__init__.py
Quick fix for #45 by creating separate socket for each send.
This line should be removed after merge to make build successful: https://github.com/Danielhiversen/PyXiaomiGateway/blob/b7407d22118529d17bbfd99050f755edfc085c74/tests/test_e2e.py#L96
> Fix race condition in a _send_cmd()

- xiaomi_gateway/__init__.py
> Do interface binding when the platform is Windows or FreeBSD

- xiaomi_gateway/__init__.py
Reverts Danielhiversen/PyXiaomiGateway#138
Because this doesn't fix the issue but could potentially break something else. See https://github.com/Danielhiversen/PyXiaomiGateway/issues/137#issuecomment-451110258
> Revert "Do interface binding when the platform is Windows or FreeBSD"

- xiaomi_gateway/__init__.py
cp. https://github.com/home-assistant/home-assistant/issues/21418
This PR supersedes the polling approach of https://github.com/home-assistant/home-assistant/pull/21116.
> Add missing leading zero of the gateway mac address

- xiaomi_gateway/__init__.py
> Add retries to zigbee device discovery

- xiaomi_gateway/__init__.py
Instead of per gateway param
@syssi As you requested :)
> Create global parameter for discovery_retries

- xiaomi_gateway/__init__.py
This is an attempt to resolve this issue: https://github.com/home-assistant/core/issues/37306
> attempt to fix binding of socket

- .travis.yml
- xiaomi_gateway/__init__.py
Try to fix travis build, not sure if this will work, but I think so.....
> Fix travis build

- xiaomi_gateway/__init__.py
Fixes: #194
Fixes: https://github.com/home-assistant/core/issues/45947
> Improve error messages to distinguish between multiple devices

- xiaomi_gateway/__init__.py
Demo script:
```
import asyncio
from xiaomi_gateway import AsyncXiaomiGatewayMulticast
gateway_ip = "192.168.1.IP"
async def asyncio_demo(loop):
def callback_func_gateway(data):
print("Gateway callback")
print(data)
multicast = AsyncXiaomiGatewayMulticast(interface = "any")
await multicast.start_listen()
multicast.register_gateway(gateway_ip, callback_func_gateway)
await asyncio.sleep(30)
multicast.stop_listen()
if __name__ == "__main__":
loop = asyncio.new_event_loop()
loop.run_until_complete(asyncio_demo(loop))
```
> Migrate to async listener
